---
title: "05_correlation"
output:
  html_document:
    toc: true
  github_document:
    toc: true
always_allow_html: true
date: "2026-01-23"
---

## Loading data

start with loading data

```{r}
  data_standardise <- read.csv("../../data/processed/credit_card_clean_standardised.csv")
```

## calculing correlation matrice

```{r}
matrice_corr <- cor(data_standardise)
```

```{r}
print(matrice_corr)
```

## saving

```{r}
write.csv(matrice_corr, "../../data/processed/matrice_corr.csv", row.names = FALSE)
```

## displing Corr matrixe

```{r}
library(kableExtra)
library(magrittr)
library(webshot2)
# 1. On prépare les données
df_corr <- as.data.frame(round(matrice_corr, 2))

# 2. On crée le tableau avec un dégradé de bleu (style Pandas/Seaborn)
# Installation si nécessaire
# install.packages("ggcorrplot")
library(ggcorrplot)
# install.packages("ggcorrplot")
library(ggplot2)
# 1. Calculer la matrice de corrélation
corr_mat <- cor(df_corr, use = "complete.obs")

# 2. Générer le graphique
ggcorrplot(corr_mat, 
           hc.order = FALSE,           # Garder l'ordre original des variables
           type = "full",              # Matrice complète
           lab = TRUE,                 # Afficher les coefficients (les chiffres)
           lab_size = 3,               # Taille des chiffres
           colors = c("#4444FF", "white", "#FF0000"), # Bleu, Blanc, Rouge
           title = "Corrélation entre les outliers des variables",
           ggtheme = theme_minimal()) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) # Incliner le texte

save_kable(df_corr, file = "../../R/images/matrice_correlation.png")
```
